# workflow 1

name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - label-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes - api-server
        run: |
          kubectl apply -f api-server/nginx.yml